### ISSUE TITLE
Version 3.0.2 [White Label] Image Quality Issue

### ISSUE THREAD

**Issue by shawnlu123** [card-io/card.io-Android-SDK#47]
Hi Card.IO team

My company currently is using Android-SDK 3.0.2 White Label Version. 
Even when we use 100% JPEG compression and full resolution, the image quality is still not ideal. 
The text on card appears looks somewhat blurry.

I double checked the extra params I can pass to the scanning activity
![screen shot 2015-03-05 at 11 24 37 am](https://cloud.githubusercontent.com/assets/10440206/6512687/9c1a89c8-c32a-11e4-940e-11af7f5fff71.png)

None of them mentioned the image quality, I wanna know if there is a way of tweaking that? Thanks!

The following are the full resolution image I captured.
![970 x 612 - b](https://cloud.githubusercontent.com/assets/10440206/6512752/09ae0050-c32b-11e4-99b3-95e6d9529fda.jpg)

![970 x 612 - f](https://cloud.githubusercontent.com/assets/10440206/6512755/0e87043c-c32b-11e4-90fe-514b15fbca3f.jpg)

Thanks advance for your help! Any resource will be helpful e.g. documentation and etc.

**Comment by dgoldman-ebay** [comment]
@shawnlu123 first, you should update to the [latest version of card.io](https://github.com/card-io/card.io-Android-SDK/releases). The features formerly available only in the special White Label version of card.io are now available in the standard version.

If I'm understanding your question correctly, you're using the `EXTRA_SUPPRESS_SCAN` feature, which asks card.io to merely identify the boundaries of a card and return an appropriately cropped and de-skewed Bitmap, without card.io also scanning for the card number. And then you are converting that Bitmap to a JPEG. And even if that final conversion is lossless, the results are more blurry than you'd like. Is all that correct?

One limitation is that although we're asking the phone's camera to autofocus, we don't have much control over how good a job it does at that. But card.io does apply its own algorithm for assessing the overall focus, and rejects any images that fall below a certain threshold.

But the greatest limitation is that card.io was created when the best available video resolution was 640x480. That remains the resolution at which card.io's entire pipeline works. So the final card-sized image will always be 428x270 pixels.

My guess is that this limitation to 428x270 pixels is what you're running up against. If so, there's nothing you can do about this problem in the immediate future.

However, for the `EXTRA_SUPPRESS_SCAN` case, which skips the part of card.io's pipeline that locates and identifies the card number, it might not be too difficult to modify our code so that it is more resolution-agnostic. We don't have time to work on this here, but all of card.io's code is now [open source](https://github.com/card-io/card.io-Android-source). So if you really want, you could take a run at this task yourself, and submit the results back to us as a Pull Request.

**Comment by shawnlu123** [comment]
Thank you so much for the timely reply. This information is really helpful.
